# Lightning Trainer configuration

_target_: lightning.Trainer
default_root_dir: ${paths.log_dir}

min_epochs: 1
max_epochs: 100

accelerator: gpu
devices: 1

precision: "16-mixed"
deterministic: true

# Reproducibility
benchmark: false
