# CSV Logger configuration
# https://lightning.ai/docs/pytorch/stable/extensions/logging.html

_target_: pytorch_lightning.loggers.CSVLogger

save_dir: ${paths.output_dir}
name: "csv"
version: null
flush_logs_every_n_steps: 50
