# Default callbacks configuration
# https://lightning.ai/docs/pytorch/stable/extensions/callbacks.html

model_checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  dirpath: ${paths.output_dir}/checkpoints
  filename: "epoch_{epoch:03d}"
  monitor: "val/mAP"
  mode: "max"
  save_last: true
  save_top_k: 3
  auto_insert_metric_name: false
  verbose: false

# early_stopping:
#   _target_: pytorch_lightning.callbacks.EarlyStopping
#   monitor: "val/mAP"
#   patience: 20
#   mode: "max"
#   min_delta: 0.0
#   verbose: false

rich_progress_bar:
  _target_: pytorch_lightning.callbacks.RichProgressBar

learning_rate_monitor:
  _target_: pytorch_lightning.callbacks.LearningRateMonitor
  logging_interval: "step"
