# Default callbacks configuration
# https://lightning.ai/docs/pytorch/stable/extensions/callbacks.html

model_checkpoint:
  _target_: lightning.pytorch.callbacks.ModelCheckpoint
  dirpath: ${paths.output_dir}/checkpoints
  filename: "epoch_{epoch:03d}"
  monitor: "val/loss"
  mode: "min"
  save_last: true
  save_top_k: 3
  auto_insert_metric_name: false
  verbose: false

early_stopping:
  _target_: lightning.pytorch.callbacks.EarlyStopping
  monitor: "val/loss"
  patience: 10
  mode: "min"
  min_delta: 0.0
  verbose: false

rich_progress_bar:
  _target_: lightning.pytorch.callbacks.RichProgressBar

learning_rate_monitor:
  _target_: lightning.pytorch.callbacks.LearningRateMonitor
  logging_interval: "step"
